# Generated by Django 5.0.3 on 2024-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('created_by', models.CharField(max_length=127)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_tmstmp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'custom report',
                'verbose_name_plural': 'custom reports',
            },
        ),
    ]
