# Generated by Django 5.0.4 on 2024-05-16 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPartiesThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger', models.IntegerField(default=0)),
                ('action', models.IntegerField(default=0)),
                ('acceptable', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='SelectedColumns',
            new_name='AllPartiesSelectedColumns',
        ),
    ]
