# Generated by Django 5.0.4 on 2024-05-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color_theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=127, null=True),
        ),
    ]
