# Generated by Django 5.0.4 on 2024-04-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='storage_limit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='used_storage',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
