# Generated by Django 5.0.4 on 2024-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='color_theme',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('dark', 'Dark'), ('light', 'Light'), ('colored', 'Colored')], default='default', max_length=127, null=True),
        ),
    ]
