# Generated by Django 5.0.4 on 2024-04-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_storage_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='storage_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='used_storage',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
