# Generated by Django 5.0.4 on 2024-05-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='last_updated_tmstmp',
            new_name='model_last_updated_tmstmp',
        ),
        migrations.AddField(
            model_name='report',
            name='report_last_updated_tmstmp',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
