# Generated by Django 5.0.4 on 2024-04-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_col',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Date column header'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_datetime_merged',
            field=models.BooleanField(default=False, verbose_name='Same column for date & time'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_masterdata',
            field=models.BooleanField(default=False, verbose_name='Master data sheet'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_col',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Time column header'),
        ),
    ]
