# Generated by Django 5.0.4 on 2024-04-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
