# Generated by Django 5.0.4 on 2024-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_data_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('SE', 'Sales Executive'), ('TC', 'Tally caller'), ('ADM', 'Admin'), ('MO', 'Machine Operator'), ('AMO', 'Ast. Machine Opt.'), ('HEL', 'Helper'), ('FI', 'Floor Incharge'), ('GI', 'Godown Incharge'), ('OFC', 'Office'), ('ACC', 'Accountant'), ('MIS', 'Misc.'), ('PC', 'Production Cordinator'), ('PUR', 'Purchase'), ('DI', 'Dispatch Incharge'), ('MI', 'Maintainance Incharge'), ('QI', 'Quality Incharge'), ('BI', 'Billing Incharge'), ('SC', 'Sales Cordinator'), ('LM', 'Lead Manager')], default='SE', max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('PRD', 'Production'), ('DIS', 'Dispatch'), ('QA', 'Quality'), ('TLY', 'Tally Calling'), ('SL', 'Sales'), ('HR', 'H.R'), ('PR', 'Purchase'), ('CF', 'C&F'), ('ACC', 'Accounts'), ('GD', 'Godown'), ('NSD', 'New Sales Division'), ('ECD', 'Existing Client Division'), ('CSD', 'Cross Sales Division'), ('BIL', 'Billing'), ('MNT', 'Maintenence'), ('IT', 'I.T')], max_length=127),
        ),
    ]
