# Generated by Django 5.0.4 on 2024-06-04 03:53

import report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_remove_employee_position_employee_job_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_dump', models.FileField(upload_to=report.models.get_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
