# Generated by Django 5.0.4 on 2024-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_dbbackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=127, unique=True)),
                ('gst_no', models.CharField(max_length=127, unique=True)),
                ('first_sale', models.DateField(blank=True, null=True)),
                ('last_sale', models.DateField(blank=True, null=True)),
                ('created_tmstmp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['customer_name'], name='report_part_custome_ce604a_idx'), models.Index(fields=['gst_no'], name='report_part_gst_no_0fa2a4_idx'), models.Index(fields=['customer_name', 'gst_no'], name='report_part_custome_58fbe6_idx')],
            },
        ),
    ]
