# Generated by Django 5.0.4 on 2024-06-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_parties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parties',
        ),
    ]
