# Generated by Django 5.0.4 on 2024-07-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_delete_parties'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSalesOrderControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=127, unique=True)),
                ('Controllable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Exceptional', 'Exceptional')], max_length=127)),
            ],
        ),
    ]
