# Generated by Django 5.0.4 on 2024-07-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_pendingsalesordercontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightChargesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=127, unique=True)),
                ('charge_per_trip', models.CharField(max_length=127)),
            ],
        ),
    ]
